name: Lint blogs metadata

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.12
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12
    - name: linter
      run: |
        python linter.py
